OpenApi compatibility Gemfire 1.15
gemfire/tanzu-gemfire-management-cf-plugin pull request #33
Opened 2022-06-09 16:20 UTC by JulianBenitez99

Fix missing information in the new format for POST and PUT endpoints.

2022-06-09 17:16 UTC, jinmeiliao approved these changes
Thanks!

2022-06-09 18:14 UTC, onichols-pivotal commented
Does this change handle both new (`x-jqFilter`) and old (`jqFilter`) field name?  I don't think any of the existing tests catch this, because all the tests of jqFilter use hardcoded sample data (swagger style, not openapi).  Maybe should duplicate each of those tests to add equivalents that test against openapi v3 sample data.

For production, I believe the plugin tolerates the lack of `jqFilter` in order to retain compatibility with very old versions of GemFire that didn't supply it.  However this field is vital to presenting a nice human-readable view of the returned data for many commands.

2022-06-09 18:15 UTC, onichols-pivotal commented on impl/common/endpoints.go
> +		commandData.ConnnectionData.LocatorAddress + "/management/v3/api-docs",
if these are tried in order, as an optimization maybe the most likely ones should be tried first? e.g. v3, then v1, then the others

2022-06-09 18:37 UTC, jmelchio requested changes
Looks good, just needs `x-jqFilter` json element support. Apologies for not bringing that up ahead of time.

2022-06-09 18:37 UTC, jmelchio commented on domain/structs.go
> +	JQFilter    string          `json:"jqFilter"`
You will need the ability to also parse `x-jqFilter` for the changes made in the newer API. I assume you can simply add an element here and do something similar to what you have done for `Definitions` and `Components`.

2022-06-09 22:01 UTC, jmelchio approved these changes
LGTM

2022-06-10 07:23 UTC, onichols-pivotal approved these changes

2022-06-10 15:04 UTC, merged